apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: ajaydabe/myapp:v3
          ports:
            - containerPort: 82
